// <auto-generated />
namespace Payroll.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class salary_obj_updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salary_obj_updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201604191442524_salary_obj_updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
