// <auto-generated />
namespace Payroll.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfkattendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfkattendance));
        
        string IMigrationMetadata.Id
        {
            get { return "201603270422471_add-fk-attendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
