// <auto-generated />
namespace Payroll.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addattendancelogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addattendancelogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201602080556529_add-attendance-log-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
