// <auto-generated />
namespace Payroll.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class runseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(runseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201602241613509_runseed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
