namespace Payroll.Entities.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class baseentit : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.employee_hours_total",
                c => new
                    {
                        TotalEmployeeHoursId = c.Int(nullable: false, identity: true),
                        EmployeeId = c.Int(nullable: false),
                        Date = c.DateTime(nullable: false, precision: 0),
                        Hours = c.Double(nullable: false),
                        Type = c.Int(nullable: false),
                        IsActive = c.Boolean(nullable: false),
                        CreateDate = c.DateTime(nullable: false, precision: 0),
                        UpdateDate = c.DateTime(nullable: false, precision: 0),
                        Owner_Id = c.String(maxLength: 128, storeType: "nvarchar"),
                    })
                .PrimaryKey(t => t.TotalEmployeeHoursId)
                .ForeignKey("dbo.AspNetUsers", t => t.Owner_Id)
                .Index(t => t.Owner_Id);
            
            AddColumn("dbo.attendance_log", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.attendance_log", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.attendance_log", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.attendance_log", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.attendance", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.attendance", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.attendance", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.attendance", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.deduction", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.deduction", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.deduction", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.deduction", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.department_manager", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.department_manager", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.department_manager", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.department_manager", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.department", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.department", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.department", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_adjustment", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.employee_adjustment", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_adjustment", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_adjustment", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_department", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_department", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_department", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_files", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.employee_files", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_files", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_files", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_hours", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.employee_hours", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_hours", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_hours", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_info", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.employee_info", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_info", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_info", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_leave", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.employee_leave", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_leave", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_leave", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_loan", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_loan", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_loan", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.loan", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.loan", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.loan", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.employee_workschedule", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_workschedule", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.employee_workschedule", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.work_schedule", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.work_schedule", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.work_schedule", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.work_schedule", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.files", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.files", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.files", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.files", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.frequency", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.frequency", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.frequency", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.frequency", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.holiday", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.holiday", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.holiday", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.leave", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.leave", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.leave", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.loan_payment", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.loan_payment", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.loan_payment", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.loan_payment", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.payment_frequency", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.payment_frequency", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.payment_frequency", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.payroll", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.payroll", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.payroll", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.payroll", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.positions", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.positions", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.positions", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.schedule", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.schedule", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.schedule", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.schedule", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.settings", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.settings", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.settings", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.settings", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            AddColumn("dbo.tax", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.tax", "CreateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.tax", "UpdateDate", c => c.DateTime(nullable: false, precision: 0));
            AddColumn("dbo.tax", "Owner_Id", c => c.String(maxLength: 128, storeType: "nvarchar"));
            CreateIndex("dbo.attendance_log", "Owner_Id");
            CreateIndex("dbo.attendance", "Owner_Id");
            CreateIndex("dbo.deduction", "Owner_Id");
            CreateIndex("dbo.department_manager", "Owner_Id");
            CreateIndex("dbo.department", "Owner_Id");
            CreateIndex("dbo.employee_adjustment", "Owner_Id");
            CreateIndex("dbo.employee_department", "Owner_Id");
            CreateIndex("dbo.employee_files", "Owner_Id");
            CreateIndex("dbo.employee_hours", "Owner_Id");
            CreateIndex("dbo.employee_info", "Owner_Id");
            CreateIndex("dbo.employee", "Owner_Id");
            CreateIndex("dbo.employee_leave", "Owner_Id");
            CreateIndex("dbo.employee_loan", "Owner_Id");
            CreateIndex("dbo.loan", "Owner_Id");
            CreateIndex("dbo.employee_workschedule", "Owner_Id");
            CreateIndex("dbo.work_schedule", "Owner_Id");
            CreateIndex("dbo.files", "Owner_Id");
            CreateIndex("dbo.frequency", "Owner_Id");
            CreateIndex("dbo.holiday", "Owner_Id");
            CreateIndex("dbo.leave", "Owner_Id");
            CreateIndex("dbo.loan_payment", "Owner_Id");
            CreateIndex("dbo.payment_frequency", "Owner_Id");
            CreateIndex("dbo.payroll", "Owner_Id");
            CreateIndex("dbo.positions", "Owner_Id");
            CreateIndex("dbo.schedule", "Owner_Id");
            CreateIndex("dbo.settings", "Owner_Id");
            CreateIndex("dbo.tax", "Owner_Id");
            AddForeignKey("dbo.attendance_log", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.attendance", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.deduction", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.department_manager", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.department", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_adjustment", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_department", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_files", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_hours", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_info", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_leave", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.loan", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_loan", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.employee_workschedule", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.work_schedule", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.files", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.frequency", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.holiday", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.leave", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.loan_payment", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.payment_frequency", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.payroll", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.positions", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.schedule", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.settings", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.tax", "Owner_Id", "dbo.AspNetUsers", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.employee_hours_total", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.tax", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.settings", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.schedule", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.positions", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.payroll", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.payment_frequency", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.loan_payment", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.leave", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.holiday", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.frequency", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.files", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.work_schedule", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_workschedule", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_loan", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.loan", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_leave", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_info", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_hours", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_files", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_department", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.employee_adjustment", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.department", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.department_manager", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.deduction", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.attendance", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.attendance_log", "Owner_Id", "dbo.AspNetUsers");
            DropIndex("dbo.employee_hours_total", new[] { "Owner_Id" });
            DropIndex("dbo.tax", new[] { "Owner_Id" });
            DropIndex("dbo.settings", new[] { "Owner_Id" });
            DropIndex("dbo.schedule", new[] { "Owner_Id" });
            DropIndex("dbo.positions", new[] { "Owner_Id" });
            DropIndex("dbo.payroll", new[] { "Owner_Id" });
            DropIndex("dbo.payment_frequency", new[] { "Owner_Id" });
            DropIndex("dbo.loan_payment", new[] { "Owner_Id" });
            DropIndex("dbo.leave", new[] { "Owner_Id" });
            DropIndex("dbo.holiday", new[] { "Owner_Id" });
            DropIndex("dbo.frequency", new[] { "Owner_Id" });
            DropIndex("dbo.files", new[] { "Owner_Id" });
            DropIndex("dbo.work_schedule", new[] { "Owner_Id" });
            DropIndex("dbo.employee_workschedule", new[] { "Owner_Id" });
            DropIndex("dbo.loan", new[] { "Owner_Id" });
            DropIndex("dbo.employee_loan", new[] { "Owner_Id" });
            DropIndex("dbo.employee_leave", new[] { "Owner_Id" });
            DropIndex("dbo.employee", new[] { "Owner_Id" });
            DropIndex("dbo.employee_info", new[] { "Owner_Id" });
            DropIndex("dbo.employee_hours", new[] { "Owner_Id" });
            DropIndex("dbo.employee_files", new[] { "Owner_Id" });
            DropIndex("dbo.employee_department", new[] { "Owner_Id" });
            DropIndex("dbo.employee_adjustment", new[] { "Owner_Id" });
            DropIndex("dbo.department", new[] { "Owner_Id" });
            DropIndex("dbo.department_manager", new[] { "Owner_Id" });
            DropIndex("dbo.deduction", new[] { "Owner_Id" });
            DropIndex("dbo.attendance", new[] { "Owner_Id" });
            DropIndex("dbo.attendance_log", new[] { "Owner_Id" });
            DropColumn("dbo.tax", "Owner_Id");
            DropColumn("dbo.tax", "UpdateDate");
            DropColumn("dbo.tax", "CreateDate");
            DropColumn("dbo.tax", "IsActive");
            DropColumn("dbo.settings", "Owner_Id");
            DropColumn("dbo.settings", "UpdateDate");
            DropColumn("dbo.settings", "CreateDate");
            DropColumn("dbo.settings", "IsActive");
            DropColumn("dbo.schedule", "Owner_Id");
            DropColumn("dbo.schedule", "UpdateDate");
            DropColumn("dbo.schedule", "CreateDate");
            DropColumn("dbo.schedule", "IsActive");
            DropColumn("dbo.positions", "Owner_Id");
            DropColumn("dbo.positions", "UpdateDate");
            DropColumn("dbo.positions", "CreateDate");
            DropColumn("dbo.payroll", "Owner_Id");
            DropColumn("dbo.payroll", "UpdateDate");
            DropColumn("dbo.payroll", "CreateDate");
            DropColumn("dbo.payroll", "IsActive");
            DropColumn("dbo.payment_frequency", "Owner_Id");
            DropColumn("dbo.payment_frequency", "UpdateDate");
            DropColumn("dbo.payment_frequency", "CreateDate");
            DropColumn("dbo.loan_payment", "Owner_Id");
            DropColumn("dbo.loan_payment", "UpdateDate");
            DropColumn("dbo.loan_payment", "CreateDate");
            DropColumn("dbo.loan_payment", "IsActive");
            DropColumn("dbo.leave", "Owner_Id");
            DropColumn("dbo.leave", "UpdateDate");
            DropColumn("dbo.leave", "CreateDate");
            DropColumn("dbo.holiday", "Owner_Id");
            DropColumn("dbo.holiday", "UpdateDate");
            DropColumn("dbo.holiday", "CreateDate");
            DropColumn("dbo.frequency", "Owner_Id");
            DropColumn("dbo.frequency", "UpdateDate");
            DropColumn("dbo.frequency", "CreateDate");
            DropColumn("dbo.frequency", "IsActive");
            DropColumn("dbo.files", "Owner_Id");
            DropColumn("dbo.files", "UpdateDate");
            DropColumn("dbo.files", "CreateDate");
            DropColumn("dbo.files", "IsActive");
            DropColumn("dbo.work_schedule", "Owner_Id");
            DropColumn("dbo.work_schedule", "UpdateDate");
            DropColumn("dbo.work_schedule", "CreateDate");
            DropColumn("dbo.work_schedule", "IsActive");
            DropColumn("dbo.employee_workschedule", "Owner_Id");
            DropColumn("dbo.employee_workschedule", "UpdateDate");
            DropColumn("dbo.employee_workschedule", "CreateDate");
            DropColumn("dbo.loan", "Owner_Id");
            DropColumn("dbo.loan", "UpdateDate");
            DropColumn("dbo.loan", "CreateDate");
            DropColumn("dbo.employee_loan", "Owner_Id");
            DropColumn("dbo.employee_loan", "UpdateDate");
            DropColumn("dbo.employee_loan", "CreateDate");
            DropColumn("dbo.employee_leave", "Owner_Id");
            DropColumn("dbo.employee_leave", "UpdateDate");
            DropColumn("dbo.employee_leave", "CreateDate");
            DropColumn("dbo.employee_leave", "IsActive");
            DropColumn("dbo.employee", "Owner_Id");
            DropColumn("dbo.employee", "UpdateDate");
            DropColumn("dbo.employee", "CreateDate");
            DropColumn("dbo.employee_info", "Owner_Id");
            DropColumn("dbo.employee_info", "UpdateDate");
            DropColumn("dbo.employee_info", "CreateDate");
            DropColumn("dbo.employee_info", "IsActive");
            DropColumn("dbo.employee_hours", "Owner_Id");
            DropColumn("dbo.employee_hours", "UpdateDate");
            DropColumn("dbo.employee_hours", "CreateDate");
            DropColumn("dbo.employee_hours", "IsActive");
            DropColumn("dbo.employee_files", "Owner_Id");
            DropColumn("dbo.employee_files", "UpdateDate");
            DropColumn("dbo.employee_files", "CreateDate");
            DropColumn("dbo.employee_files", "IsActive");
            DropColumn("dbo.employee_department", "Owner_Id");
            DropColumn("dbo.employee_department", "UpdateDate");
            DropColumn("dbo.employee_department", "CreateDate");
            DropColumn("dbo.employee_adjustment", "Owner_Id");
            DropColumn("dbo.employee_adjustment", "UpdateDate");
            DropColumn("dbo.employee_adjustment", "CreateDate");
            DropColumn("dbo.employee_adjustment", "IsActive");
            DropColumn("dbo.department", "Owner_Id");
            DropColumn("dbo.department", "UpdateDate");
            DropColumn("dbo.department", "CreateDate");
            DropColumn("dbo.department_manager", "Owner_Id");
            DropColumn("dbo.department_manager", "UpdateDate");
            DropColumn("dbo.department_manager", "CreateDate");
            DropColumn("dbo.department_manager", "IsActive");
            DropColumn("dbo.deduction", "Owner_Id");
            DropColumn("dbo.deduction", "UpdateDate");
            DropColumn("dbo.deduction", "CreateDate");
            DropColumn("dbo.deduction", "IsActive");
            DropColumn("dbo.attendance", "Owner_Id");
            DropColumn("dbo.attendance", "UpdateDate");
            DropColumn("dbo.attendance", "CreateDate");
            DropColumn("dbo.attendance", "IsActive");
            DropColumn("dbo.attendance_log", "Owner_Id");
            DropColumn("dbo.attendance_log", "UpdateDate");
            DropColumn("dbo.attendance_log", "CreateDate");
            DropColumn("dbo.attendance_log", "IsActive");
            DropTable("dbo.employee_hours_total");
        }
    }
}
